---
title: "Late Stage Associations"
author: "Andrew Zimolzak, MD, MMSc"
date: "`r Sys.Date()`"
output: pdf_document
---



# Intro

```{r setup, include=FALSE}
library(dplyr)
library(readr)
library(ggplot2)
library(knitr)
library(tidyr)
library(Hmisc)
```

```{r read, include=FALSE}
L <- read_csv("VA Lung comprehensive.csv")
C <- read_csv("VA Colon comprehensive.csv")
```

Columns I will analyze:

- PatientSex
- PatientRace
- PatientAgeCapped
- IsLate




# Colon

## Sex (n.s.)

```{r code-sex, echo=FALSE}
C_coded <- C %>% mutate(
  Sex = case_when(
    PatientSex == 1 ~ "M",
    TRUE ~ "F"
  )
)

colon_sex <- table(C_coded$Sex, C_coded$IsLate)
```

```{r test-sex, echo=FALSE}
fisher.test(colon_sex)

chi_col_s <- chisq.test(colon_sex)
chi_col_s
p_col_sex <- chi_col_s$p.value
```

## Race (significant)

```{r code-race, echo=FALSE}
C_coded_r <- C_coded %>%  # Should use this one for all analyses
  mutate(
    Race = case_when(
      PatientRace == 3 ~ "White",
      PatientRace == 1 ~ "Black",
      PatientRace == 2 ~ "Hispanic",
      TRUE ~ "Other"
    )
  )

colon_race <- table(C_coded_r$Race, C_coded_r$IsLate)
```

```{r race-fisher, echo=FALSE}
fisher.test(colon_race)

chi_col_race <- chisq.test(colon_race)
chi_col_race
p_col_race <- chi_col_race$p.value
```

## Age (n.s.)

```{r plot-age, echo=FALSE}
ggplot(data = C, aes(
  PatientAgeCapped,
  fill = as.factor(IsLate),
  color = as.factor(IsLate)
  )) +
  geom_density(alpha=0.3)
```
```{r wilcox-age, echo=FALSE}
col_wilcox <- wilcox.test(
  C %>% filter(IsLate == 1) %>% pull(PatientAgeCapped),
  C %>% filter(IsLate == 0) %>% pull(PatientAgeCapped)
)

col_wilcox
p_col_age <- col_wilcox$p.value
```




# Lung

```{r cleaning-coding, echo=FALSE}
L_coded <- L %>%
  mutate(
    Sex = case_when(
      PatientSex == 1 ~ "M",
      TRUE ~ "F"
    ),
    Race = case_when(
      PatientRace == 3 ~ "White",
      PatientRace == 1 ~ "Black",
      PatientRace == 2 ~ "Hispanic",
      TRUE ~ "Other"
    )
  )
```

## Sex (significant)

```{r sex, echo=FALSE}
s_table <- table(L_coded$Sex, L_coded$IsLate)

fisher.test(s_table)

chi_lung_sex <- chisq.test(s_table)
chi_lung_sex
p_lung_sex <- chi_lung_sex$p.value
```

## Race (significant)

```{r race, echo=FALSE}
race <- table(L_coded$Race, L_coded$IsLate)

fisher.test(race, workspace = 2000000/4)

chi_lung_race <- chisq.test(race)
chi_lung_race
p_lung_race <- chi_lung_race$p.value
```

## Age (significant)

```{r age-plot-lung, echo=FALSE}
ggplot(data = L, aes(
  PatientAgeCapped,
  fill = as.factor(IsLate),
  color = as.factor(IsLate))
  ) +
  geom_density(alpha=0.3)
```

```{r age-wilcox-t, echo=FALSE}
lung_wilcox <- wilcox.test(
  L %>% filter(IsLate == 1) %>% pull(PatientAgeCapped),
  L %>% filter(IsLate == 0) %>% pull(PatientAgeCapped)
)

lung_wilcox
p_lung_age <- lung_wilcox$p.value

t.test(
  L %>% filter(IsLate == 1) %>% pull(PatientAgeCapped),
  L %>% filter(IsLate == 0) %>% pull(PatientAgeCapped)
)
```




# Appendix: Detective work on race

Colon and lung, respectively:

```{r detective, echo=FALSE, message=FALSE, warning=FALSE}
C_coded_r %>%
  group_by(Race, PatientRace) %>%
  summarise(count = n()) %>%
  arrange(PatientRace) %>%
  kable()

L_coded %>%
  group_by(Race, PatientRace) %>%
  summarise(count = n()) %>%
  arrange(PatientRace) %>%
  kable()
```




# Association tables

```{r final-tidying, echo=FALSE}
colon_final <- C_coded_r %>%
  mutate(cancer_type = "Colon")

lung_final <- L_coded %>%
  mutate(cancer_type = "Lung")

all_data <- bind_rows(colon_final, lung_final) %>%
  select(Sex, Race, cancer_type, PatientAgeCapped, IsLate, StageOfCancer,
         TypeOfCancer, TypeOfEmergencyEvent, EP) %>%
  mutate(IsLate = case_when(
    IsLate == 0 ~ "Early",
    IsLate == 1 ~ "Advanced",
    TRUE ~ "unknown"
  ))
```

```{r comprehensive-assoc, echo=FALSE}
assoc_r <- all_data %>%
  count(cancer_type, IsLate, Race) %>%
  mutate(Factor = "Race") %>% 
  rename(Level = Race)

assoc_s <- all_data %>%
  count(cancer_type, IsLate, Sex) %>%
  mutate(Factor = "Sex") %>% 
  rename(Level = Sex)

assoc <- bind_rows(assoc_r, assoc_s) %>% 
  pivot_wider(names_from = c(cancer_type, IsLate), values_from = n) %>%
  mutate(
    Colon_Denom = Colon_Early + Colon_Advanced,
    Lung_Denom = Lung_Early + Lung_Advanced,
    Colon_Rate = round(Colon_Advanced / Colon_Denom * 100, 1),
    Lung_Rate = round(Lung_Advanced / Lung_Denom * 100, 1),
    p_colon = case_when(Factor == "Race" ~ round(p_col_race, 3), TRUE ~ round(p_col_sex, 3)),
    p_lung = case_when(Factor == "Race" ~ round(p_lung_race, 3), TRUE ~ round(p_lung_sex, 3))
  ) %>%
  select(
    Factor, Level,
    Colon_Advanced, Colon_Denom, Colon_Rate, p_colon,
    Lung_Advanced, Lung_Denom, Lung_Rate, p_lung
  )
```

```{r displayable, echo=FALSE}
assoc %>% 
  arrange(Factor, desc(Lung_Denom)) %>% 
  unite(Colon_Advanced, Colon_Denom, col="Colon_VA", sep = " / ") %>% 
  unite(Colon_VA, Colon_Rate, col="Colon_VA", sep=" (") %>% 
  unite(Lung_Advanced, Lung_Denom, col="Lung_VA", sep = " / ") %>% 
  unite(Lung_VA, Lung_Rate, col="Lung_VA", sep=" (") %>% 
  mutate(across(c(Colon_VA, Lung_VA), ~ paste0(.x, ")"))) %>% 
  kable()
```

```{r fancy, echo=FALSE}
q123 <- list(
  q1 = ~quantile(.x, 0.25, na.rm = TRUE),
  median = ~quantile(.x, 0.5, na.rm = TRUE),
  q3 = ~quantile(.x, 0.75, na.rm = TRUE),
  mean = ~round(mean(.x, na.rm=TRUE), 2),
  sd = ~round(sd(.x, na.rm = TRUE), 2)
)

all_data %>% 
  group_by(cancer_type, IsLate) %>% 
  summarise(across(PatientAgeCapped, q123)) %>% 
  unite(PatientAgeCapped_median, PatientAgeCapped_q1, col="Median_Q1", sep = " (") %>% 
  unite(Median_Q1, PatientAgeCapped_q3, col = "Median_Q1_Q3", sep = " - ") %>% 
  unite(PatientAgeCapped_mean, PatientAgeCapped_sd, col="Mean_SD", sep = " (") %>% 
  mutate(across(c(Median_Q1_Q3, Mean_SD), ~ paste0(.x, ")"))) %>% 
  kable()
```




# For later

Package `Hmisc` and function `binconf()` ?

```{r ci-example, echo=TRUE}
X <- data.frame(succ = c(52,76,64,68), denom=c(90,100,96,100))

X %>% mutate(
  ciw.poi = binconf(succ, denom)[,"PointEst"],
  ciw.low = binconf(succ, denom)[,"Lower"],
  ciw.upp = binconf(succ, denom)[,"Upper"],
  
  cia.poi = binconf(succ, denom, method = "asymptotic")[,"PointEst"],
  cia.low = binconf(succ, denom, method = "asymptotic")[,"Lower"],
  cia.upp = binconf(succ, denom, method = "asymptotic")[,"Upper"],
) %>%
  kable()
```
